version: '3.5'
services:

    db:
        container_name: library_database
        image: mongo:3.1
        environment:
            - MONGO_INITDB_ROOT_DB=${MONGO_INITDB_ROOT_DB}
            - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
            - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_DB}
        ports:
        - '27017:27017'