version: '3.5'
services:

    db:
        container_name: app_database
        image: mongo:3.1
        environment:
            - MONGO_INITDB_ROOT_DB=${MONGO_INITDB_ROOT_DB}
            - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
            - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_DB}
        ports:
        - '27017:27017'

    mbdb:
        container_name: app_metabase
        image: postgres:latest
        environment:
            - MB_DB_TYPE=${MB_DB_TYPE}
            - MB_DB_DBNAME=${MB_DB_DBNAME}
            - MB_DB_PORT=${MB_DB_PORT}
            - MB_DB_USER=${MB_DB_USER}
            - MB_DB_PASS=${MB_DB_PASS}
            - MB_DB_HOST=${MB_DB_HOST}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - METABASE_PASSWORD=${METABASE_PASSWORD}
        ports:
        - '5432:5432'

    