name: CI_Build

# on: [push]

on: 
  workflow_run: 
    workflows: ["CI_Tests"]
    branches: [main]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success'}}
    defaults:
      run:
        working-directory: ./


    steps:
    - uses: actions/checkout@v2


    - name: docker-compose up
      run: docker-compose up -d


    - name: docker-compose down
      run: docker-compose down
    

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2


    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}


    - name: Build and push
      id: docker_build_server
      uses: docker/build-push-action@v2
      with:
        context: ./app
        file: ./app/Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/trabalho-individual-2022-2-server:latest