name: CI_Lint

on: [push]

jobs:
    server_lint:
      runs-on: ubuntu-latest

      steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Setup Python ${{ matrix.python-version }}
          uses: actions/setup-python@v2
          with:
            python-version: 3.8

        - name: Pip Install requirements
          run: |
            pip install -r requirements.txt

        - name: Server Lint Check
          run: |
            pylint ./**/*.py